name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Gulp CLI
        run: npm install -g gulp-cli

      - name: Install Dependencies
        run: npm ci

      - name: Build Production Version
        run: npx gulp build

      - name: Validate HTML with node-w3c-validator
        run: npm run html

      - name: Check EditorConfig
        run: npm run code

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app
