name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Gulp CLI
        run: npm install -g gulp-cli

      - name: Install project dependencies
        run: npm install

      - name: Build with Gulp
        run: gulp build # Замените на команду Gulp, которая собирает ваш проект

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./app # Замените на путь к собранному проекту
          publish_branch: gh-pages # Замените на ветку, в которую будет производиться деплой
          enable_jekyll: false # Установите в true, если используете Jekyll в вашем проекте
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
