name: Gulp CI/CD

on:
  push:
    branches:
      - main # Измените на вашу основную ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Измените на желаемую версию Node.js

      - name: Install project dependencies
        run: npm install

      - name: Build with Gulp
        run: gulp build # Замените на ваш таск для сборки проекта

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./app/index.html # Путь к каталогу, содержащему собранные файлы (измените, если требуется)
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
